// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_x8esJvU5Azjc_lkMvV5zDTWN0wHlFQQ',
    appId: '1:139709011723:web:c468f1d98af204c5a2b40e',
    messagingSenderId: '139709011723',
    projectId: 'fir-learn-7e629',
    authDomain: 'fir-learn-7e629.firebaseapp.com',
    storageBucket: 'fir-learn-7e629.appspot.com',
    measurementId: 'G-CLN48NHQLD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCcMRN85Xez7NJ1HfQW9VFTa0l8g-mZ1pc',
    appId: '1:139709011723:android:eeae3a51fb0ae1a6a2b40e',
    messagingSenderId: '139709011723',
    projectId: 'fir-learn-7e629',
    storageBucket: 'fir-learn-7e629.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAgclQ5PYhcZ4PCkbEYQclJM4ESvzRQeiU',
    appId: '1:139709011723:ios:4ae96529051e7255a2b40e',
    messagingSenderId: '139709011723',
    projectId: 'fir-learn-7e629',
    storageBucket: 'fir-learn-7e629.appspot.com',
    iosBundleId: 'com.example.firebaseLearn',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAgclQ5PYhcZ4PCkbEYQclJM4ESvzRQeiU',
    appId: '1:139709011723:ios:e5f2cec111a06d3ba2b40e',
    messagingSenderId: '139709011723',
    projectId: 'fir-learn-7e629',
    storageBucket: 'fir-learn-7e629.appspot.com',
    iosBundleId: 'com.example.firebaseLearn.RunnerTests',
  );
}
